### ISSUE TITLE
ros_workspace/src/tractor/src/collision/loader.cpp:18:10: fatal error: bullet/HACD/hacdHACD.h: No such file or directory

### ISSUE THREAD

**Issue by senbinyu** [TAMS-Group/efficient-motion-reconstruction#1]
Thanks for your interesting work. I try to reproduce, put all the submodules directories in the "src" folder in the ros workspace. The file tree of ros workspace is as following. Is it correct?
![tree](https://github.com/TAMS-Group/efficient-motion-reconstruction/assets/42667259/ef205a89-e509-4fd9-8d03-be5d9aab9eaa)

But when I try to use catkin_make, there's an error in the title: can not find "bullet/HACD/hacdHACD.h". I read the CMakeLists.txt in tractor submodule and found it needs a lib called HACD-float64. Does the error come from there?
![hacd](https://github.com/TAMS-Group/efficient-motion-reconstruction/assets/42667259/3d8bd1c5-9744-41d4-825a-61f02f910fe7)

**Comment by cheeseJelly** [comment]
Did you solve it? I have same problem.

`src/efficient-motion-reconstruction/tractor/src/collision/loader.cpp:18:10: fatal error: bullet/HACD/hacdHACD.h: No such file or directory
   18 | #include <bullet/HACD/hacdHACD.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by v4hn** [comment]
`apt install libbullet-extras-dev`

**Comment by senbinyu** [comment]
@cheeseJelly @v4hn 
Sorry for the late, I came back to this project today. After I fixed the library dependencies problems shown above, I encountered a compilation error using catkin_make in ros_workspace. Unfortunately, I can not find reasonable solutions on google. I'm sure there's no problem with the compatibility of pybind11 and pybind11_catkin. The error comes from tractor module: /opt/ros/melodic/include/pybind11_catkin/pybind11/pybind11.h:789:7: error: using typedef-name ‘using module = class pybind11::module_’ after ‘class’ class module : public object xxx. Could you give me a quick help? Really appreciate.
![pybind11_catkin](https://github.com/TAMS-Group/efficient-motion-reconstruction/assets/42667259/2253a3d0-0160-40ff-ae91-59ef35695426)
